Type 'help' for list of commands.
TEXT main.addr_arithm(SB) addr_arithm.go
	addr_arithm.go:13	0x4614b0	4883ec18		sub rsp, 0x18
	addr_arithm.go:13	0x4614b4	48896c2410		mov qword ptr [rsp+0x10], rbp
	addr_arithm.go:13	0x4614b9	488d6c2410		lea rbp, ptr [rsp+0x10]
	addr_arithm.go:13	0x4614be	48c744243000000000	mov qword ptr [rsp+0x30], 0x0
	addr_arithm.go:14	0x4614c7	488b442420		mov rax, qword ptr [rsp+0x20]
	addr_arithm.go:14	0x4614cc	4889442408		mov qword ptr [rsp+0x8], rax
	addr_arithm.go:15	0x4614d1	48c7042404000000	mov qword ptr [rsp], 0x4
	addr_arithm.go:16	0x4614d9	488b442428		mov rax, qword ptr [rsp+0x28]
	addr_arithm.go:16	0x4614de	48c1e002		shl rax, 0x2
	<autogenerated>:1	0x4614e2	4803442408		add rax, qword ptr [rsp+0x8]
	<autogenerated>:1	0x4614e7	8400			test byte ptr [rax], al
	<autogenerated>:1	0x4614e9	488b00			mov rax, qword ptr [rax]
	<autogenerated>:1	0x4614ec	4889442430		mov qword ptr [rsp+0x30], rax
	<autogenerated>:1	0x4614f1	488b6c2410		mov rbp, qword ptr [rsp+0x10]
	<autogenerated>:1	0x4614f6	4883c418		add rsp, 0x18
	<autogenerated>:1	0x4614fa	c3			ret
exit
